### ISSUE TITLE
ledger v3

### ISSUE THREAD

**Issue by orlandow** [AlexanderAA/ledger_binaries_windows#1]
I started using ledger a few weeks ago and I would love to use its latest features but this is the only version of ledger for windows I've found.

Do you by any chance have compiled ledger 3 binaries?

Thanks a lot.

**Comment by AlexanderAA** [comment]
I guess that it might be possible to compile ledger 3 on windows without modifications - install cygwin and libraries required (check https://github.com/ledger/ledger/blob/next/INSTALL.md) and then try to compile.

I do not have windows machine to experiment with that at the moment. If you can setup windows, cygwin and dependencies on a VPS, I might be able to help.

**Comment by orlandow** [comment]
Thanks for the response.

I got it to compile but now I'm getting the `ledger.exe` file and a `libledger-3.dll` and a lot of other files.

`libledger-3.dll` is over `100 MB`, I noticed your binaries are less than `3 MB` and the files are different...

Am I including something that is not required or missing some optimization flag or something?

**Comment by AlexanderAA** [comment]
I do not think you are missing anything. Do not try to compare ledger 2 and 3, I believe that they are quite different. 

Does ledger.exe work? Is there a test suite which you can run to verify that? 

Try to experiment with upx and similar software. And, please share you binaries, people ask for them sometimes.

**Comment by orlandow** [comment]
Thanks.

I tried upx and managed to reduce the total size to 28 MB, I'll open a PR tomorrow...

**Comment by Dapuva76** [comment]
could you upload the binaries? I just got into using ledger with emacs, would be very interested in a more up-to-date version.

**Comment by orlandow** [comment]
Done, I tried to pack every dependency so it runs on a PC without cygwin installed, that's why the zip is almost 30 MB

**Comment by Dapuva76** [comment]
You're the best. Thanks for the quick reply!

**Comment by Dapuva76** [comment]
Hmm ok somethings wrong with the way filenames get processed. This is what happens when I try to use it:

Error: Cannot read journal file "/cygdrive/c/Users/Dapuva76/c:/Users/Dapuva76/Docu
ments/ledger/ledger.dat"

The file ledger.dat is of course located at c:/Users/Dapuva76/Documents/ledger/ledger.dat

**Comment by orlandow** [comment]
Hmm... I see... try using a relative path: `ledger -f "~/documents/ledger/ledger.dat" balance`. That's how I use it.

I don't know what's wrong though... perhaps I messed something compiling it, I hadn't used cygwin before and just followed some tutorial
