### ISSUE TITLE
Seems it doesn't support .ledgerrc in home directory.

### ISSUE THREAD

**Issue by kunedo** [AlexanderAA/ledger_binaries_windows#7]
Hi,

I create a `.ledgerrc` file in my home directory `C:\Users\user`，`.ledgerrc` likes:
`--file e:\data\ledger.lgr`

And when I run `> ledger bal`, it gives the folowing error:
`Error: No journal file was specified (please use -f)`

`e:\data\ledger.lgr` file is existence.

ledger version is 3.1.2.

**Comment by alensiljak** [comment]
If you need a workaround, it seems that it does support the rc file in the current directory.

**Comment by kunedo** [comment]
> If you need a workaround, it seems that it does support the rc file in the current directory.

Thinks, I wrote a bat, like:

``` bat
@SETLOCAL
@SET PATH=%~dp0;%PATH%
@SET HOME=%~dp0
@START
@ENDLOCAL
```

and it works.
