### ISSUE TITLE
v3.1.3

### ISSUE THREAD

**Issue by alensiljak** [AlexanderAA/ledger_binaries_windows#8]
https://github.com/ledger/ledger/releases/tag/v3.1.3

Please! :)

**Comment by tbm** [comment]
Any progress on this?

I'm updating https://www.ledger-cli.org/download.html and noticed the Windows binary is out of date.

**Comment by alensiljak** [comment]
As a side note, a possible workaround on Windows might be to run Windows Subsystem for Linux and use the Linux version.

**Comment by FullofQuarks** [comment]
I've submitted a pull request #9 for this issue

**Comment by fraga** [comment]
Great job @FullofQuarks thanks!

**Comment by AlexanderAA** [comment]
Thanks @FullofQuarks, would you be able to add the build instructions for the 3.1.3 binary you just submitted? I hope that will help to automate the process eventually.

**Comment by FullofQuarks** [comment]
I also used a slightly modified version of https://github.com/maxwell-k/ledger-windows-build instructions (did not have to perform step 5)

**Comment by alensiljak** [comment]
Thanks!
